### ISSUE TITLE
displayed numbers of first vaccination most likely overestimated

### ISSUE THREAD

**Issue by leinad76** [fhinder/MMM-Covid19-Vaccination#2]
Thanks a lot for the nice module!

I was wondering about the given percentage for first time vaccinations and compared it with the numbers given at the RKI dashboard (https://impfdashboard.de).

Unfortunately, for me it looks like that the value "cumsum_latest" in the morgenpost json file is not right (the total numbers are too high). It seems, that "cumsum_latest" is the sum of first and second vaccinations. If one subtract "cumsum2_latest" from "cumsum_latest" one get exactly the same numbers given at morgenpost as well as on the RKI dashboard.
You might want to crosscheck the total numbers again? Thanks a lot, I really appreciate!

**Comment by fhinder** [comment]
Hello @leinad76 ,

thanks for the feedback to the module. 

Concerning the bug you found:
I checked the numbers: You are right, the calculation was done in a wrong way. I changed the calculation and now the same numbers as on RKI dashbaord are shown.
With the commit 3effed25b0219f5dd20465ca7ec69c0f64b46401 the issue is fixed.
